apiVersion: v1
kind: Pod
metadata:
  name: debian
  labels:
    app: web
spec:
  restartPolicy: Never
  containers:
    - name: debian
      image: debian:latest
      command: [ "tail", "-f", "/dev/null" ]
      resources:
        requests:
          cpu: "0.1"
          memory: "100Mi"
        limits:
          cpu: "0.1"
          memory: "100Mi"
