apiVersion: v1
kind: Pod
metadata:
  name: debian
  labels:
    app: web
spec:
  containers:
    - name: debian
      image: debian:bookworm-slim
      command: ["/bin/bash"]
      args: ["-c", "sleep 3600"]
      resources:
        requests:
          cpu: "0.1"
          memory: "100Mi"
        limits:
          cpu: "0.1"
          memory: "100Mi"
