apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-kel-deployment
  namespace: tutorial
  labels:
    app: nginx
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        lalala: lololo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
