apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: tutorial
  labels: 
    app: my-first-app
    type: random
    key1: value1
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        cpu: "0.1"
        memory: "100Mi"
      limits:
        cpu: "0.1"
        memory: "100Mi"
